version: "3"

services:
  caddy:
    build:
      context: ./
    volumes:
      - /var/volumes/ek-zotero:/srv
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ek-zotero.rule=Host(`ek-zotero.rknt.de`)"
      - "traefik.http.routers.ek-zotero.entrypoints=websecure"
      - "traefik.http.routers.ek-zotero.tls.certresolver=myresolver"
      - "traefik.http.services.ek-zotero.loadbalancer.server.port=80"
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
